In [1]:
import pandas as pd

In [17]:
historique=pd.read_csv("../Files/historiquevelov.csv",sep=";",decimal=",")

In [18]:
historique.head()

,horodate,number,status,total_stands,main_stands,overflow_stands
0,2023-03-27 17:33:26+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ...","{'capacity': 20, 'availabilities': {'bikes': 0...","{'capacity': 100, 'availabilities': {'bikes': ..."
1,2023-03-27 17:32:45+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ...","{'capacity': 20, 'availabilities': {'bikes': 0...","{'capacity': 100, 'availabilities': {'bikes': ..."
2,2023-03-27 17:31:10+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ...","{'capacity': 20, 'availabilities': {'bikes': 0...","{'capacity': 100, 'availabilities': {'bikes': ..."
3,2023-03-27 17:31:08+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ...","{'capacity': 20, 'availabilities': {'bikes': 0...","{'capacity': 100, 'availabilities': {'bikes': ..."
4,2023-03-27 17:28:09+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ...","{'capacity': 20, 'availabilities': {'bikes': 0...","{'capacity': 100, 'availabilities': {'bikes': ..."

In [19]:
historique = historique.drop(columns=['main_stands','overflow_stands'])
historique['horodate'] = pd.to_datetime(historique['horodate'])

In [20]:
historique.head()

,horodate,number,status,total_stands
0,2023-03-27 17:33:26+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ..."
1,2023-03-27 17:32:45+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ..."
2,2023-03-27 17:31:10+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ..."
3,2023-03-27 17:31:08+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ..."
4,2023-03-27 17:28:09+02:00,1,CLOSED,"{'capacity': 120, 'availabilities': {'bikes': ..."

In [25]:
historique.to_csv('../Data/historique.csv', index=False)

Création du fichier historique de création des pistes cyclables

In [18]:
pistes=pd.read_csv("../Files/pistes_cyclables.csv",sep=";",decimal=",")
pistes.head()

,nom,commune1,insee1,commune2,insee2,reseau,financementac,typeamenagement,typeamenagement2,positionnement,...,localisation,typologiepiste,revetementpiste,domanialite,reglementation,zonecirculationapaisee,anneelivraison,longueur,observation,gid
0,Rue de Boutras,Grigny,69096.0,NaN,NaN,Réseau secondaire,PROX/FIC DGEEP/VTP,Double sens cyclable,NaN,Unilatérale unidirectionnelle,...,Sur chaussée,NaN,NaN,Métropole,Contresens (sens réservé),Zone 30,2019.0,221.41,Arrêté n° AR 2019/001 du 14/01/2019 // ABS de ...,4451
1,Allée du Parc Technologique,Saint-Priest,69290.0,NaN,NaN,Réseau de desserte,OR DIEM/STEP,Voie verte,NaN,Sans objet,...,Sans objet,NaN,NaN,Métropole,Voie verte,NaN,2014.0,392.91,NaN,2252
2,Chemin des Grenettes,Quincieux,69163.0,NaN,NaN,Réseau de desserte,PROX/FIC DGEEP/VTP,Double sens cyclable,NaN,Unilatérale unidirectionnelle,...,Sur chaussée,NaN,NaN,Métropole,Contresens (sens réservé),NaN,2021.0,1150.48,Arrêté n°2020/204 le 08/12/20,6416
3,Bassin de Minerve,Saint-Priest,69290.0,NaN,NaN,Réseau de desserte,PPI (DMOU),Voie verte,NaN,Sans objet,...,Sans objet,Autre,Matériaux non liés (sable compacté et stabilisé),Métropole,Voie verte,NaN,2015.0,121.06,NaN,2512
4,Rue Condorcet,Saint-Priest,69290.0,NaN,NaN,Réseau de desserte,PPI DGEEP VTP,Voie verte,NaN,Sans objet,...,Sans objet,Autre,Matériaux non liés (sable compacté et stabilisé),Métropole,Voie verte,NaN,2014.0,150.11,NaN,2323

On garde uniquement les colonnes nécessaires à l'affichage

In [19]:
pistes = pistes[['nom', 'commune1','anneelivraison']]
pistes['anneelivraison'] = pistes['anneelivraison'].fillna(0).astype(int)

In [20]:
pistes.head()

                           nom      commune1  anneelivraison
0               Rue de Boutras        Grigny            2019
1  Allée du Parc Technologique  Saint-Priest            2014
2         Chemin des Grenettes     Quincieux            2021
3            Bassin de Minerve  Saint-Priest            2015
4                Rue Condorcet  Saint-Priest            2014

In [21]:
pistes[pistes['anneelivraison'] == 0]

                             nom                commune1  anneelivraison
11             Rue des Collières                   Mions               0
24        Rue du Chêne prolongée                Chassieu               0
51             Rue du Collovrier                  Écully               0
53               Rue du Dauphiné                  Corbas               0
54              Avenue de Verdun                 Meyzieu               0
...                          ...                     ...             ...
4028  Rond-point Marennes/Mermoz                  Corbas               0
4029  Boulevard Laurent bonnevay            Villeurbanne               0
4031          Avenue de l'Europe        Rillieux-la-Pape               0
4071             Pont de la Soie          Vaulx-en-Velin               0
4150               Route de Lyon  Rochetaillée-sur-Saône               0

[556 rows x 3 columns]

In [22]:
pistes.to_csv('../Data/historique_pistes.csv', index=False)